import assert from 'node:assert/strict'
import {readFileSync} from 'node:fs'
const source=readFileSync(new URL('../src/utils/yamada.js',import.meta.url),'utf8')
const {MODES,conversations,memory,addMemory}=await import('data:text/javascript;base64,'+Buffer.from(source).toString('base64'))
const old={id:'old-person',name:'A',avatarId:'photo-id',friendScore:70,communication:{relationshipStage:7,stageChecks:{7:[true]},conversationLog:[{id:'old',date:'2026-09-01',topics:'old topic',theirResponse:'old reply'}]},notes:{commonTopics:'common',lifeStory:{childhood:'retained'},entries:[{id:'note',text:'retained'}]},photos:[{id:'photo2'}],events:[{id:'event',text:'retained'}]}
const before=structuredClone(old)
const next=addMemory(old,' new memory ','2026-09-24','new')
assert.deepEqual(old,before,'updates must not mutate the old record')
assert.equal(next.friendScore,70)
assert.equal(next.communication.relationshipStage,7)
assert.deepEqual(next.communication.stageChecks,old.communication.stageChecks)
for(const key of ['notes','photos','events','avatarId'])assert.deepEqual(next[key],old[key])
assert.deepEqual(next.communication.conversationLog[1],old.communication.conversationLog[0])
assert.equal(memory(next),'new memory')
assert.equal(memory({...next,yamada:{remember:'promise'}}),'promise')
assert.equal(addMemory(next,'   ','2026-09-24','empty'),next)
const earlier=addMemory(next,'backdated','2026-08-20','earlier')
assert.equal(memory(earlier),'new memory')
assert.equal(earlier.lastInteractionDate,'2026-09-24')
assert.deepEqual(conversations({communication:{conversationLog:null}}),[])
assert.equal(memory({notes:{commonTopics:'remember'}}),'remember')
assert.equal(new Set(MODES.map(x=>x.id)).size,3)
assert.ok(MODES.every(x=>x.title&&x.voice&&x.note))
const backup={format:'intimate-backup',version:2,self:{name:'self',practice:{day:365,pins:['trust']},yamadaMode:'friends'},people:[next],assets:{}}
assert.deepEqual(JSON.parse(JSON.stringify(backup)),backup)
for(const file of ['SelfPage.jsx','SelfSettings.jsx','MainListCommunication.jsx','CommunicationPersonPage.jsx']){
  const code=readFileSync(new URL('../src/components/'+file,import.meta.url),'utf8')
  assert.ok(!/from ['"].*(friendLogic|conversationFlow|stageGuidance|hanshengCorpus|selfPractice)/.test(code),file+' must not load old coaching systems')
}
console.log('PASS: legacy data preservation, blank input, dates, pinned memory, modes, backup, removed coaching dependencies')
const stagesSource=readFileSync(new URL('../src/utils/yamadaStages.js',import.meta.url),'utf8')
const {FRIEND_GUIDES,SOMEONE_GUIDES,getStage,resolveMode,setStage}=await import('data:text/javascript;base64,'+Buffer.from(stagesSource).toString('base64'))
for(const guides of [FRIEND_GUIDES,SOMEONE_GUIDES]){
  assert.deepEqual(guides.map(x=>x.id),[1,2,3,4,5,6,7,8,9,10])
  assert.ok(guides.every(x=>['title','sign','action','say','attitude'].every(k=>typeof x[k]==='string'&&x[k].length>0)))
}
assert.equal(getStage(old),7,'restore the legacy relationship stage')
for(const invalid of [null,undefined,0,11,-1,1.5,true,false,'bad']) assert.equal(getStage({communication:{relationshipStage:invalid}}),null)
assert.equal(getStage({communication:{relationshipStage:'10'}}),10)
for(const selfGender of ['男','女'])for(const gender of ['男','女']){
  assert.deepEqual(resolveMode({gender,yamada:{mode:'someone'}},{gender:selfGender,yamadaMode:'everyday'}),{id:gender===selfGender?'friends':'someone',automatic:true})
}
assert.equal(resolveMode({gender:'female'},{gender:'男性'}).id,'someone')
assert.deepEqual(resolveMode({gender:''},{gender:'男'}),{id:null,automatic:false})
assert.deepEqual(resolveMode({gender:'other',yamada:{mode:'friends'}},{gender:'男'}),{id:'friends',automatic:false})
assert.deepEqual(resolveMode({gender:'女',yamada:{mode:'someone'}},{gender:''}),{id:'someone',automatic:false})
const staged=setStage(old,10)
assert.equal(getStage(staged),10)
assert.equal(getStage(old),7)
assert.deepEqual(staged.communication.conversationLog,old.communication.conversationLog)
assert.deepEqual(staged.notes,old.notes)
assert.deepEqual(staged.photos,old.photos)
assert.equal(staged.friendScore,70,'stage updates must not rewrite legacy scores')
assert.equal(setStage(old,11),old)
assert.equal(getStage(setStage(staged,null)),null)
assert.equal(getStage(addMemory(staged,'another memory','2026-09-24','another')),10,'logging must not auto-level')
assert.equal(getStage(JSON.parse(JSON.stringify(staged))),10)
console.log('PASS: 20 complete stage guides, legacy stage restore, gender auto-switch in both directions, unspecified/manual modes, stage changes and backup')
